### ISSUE TITLE
과제 #1 제출 전 확인 사항

### ISSUE THREAD

**Issue by moonkorea00** [pre-onboarding-frontend-7-team-3/bestTodoApp#1]
- storage 유틸 함수 추가
 - 리드미 [시멘틱한 마크업](https://github.com/pre-onboarding-frontend-7-team-3/bestTodoApp#%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-%EC%A0%84) 수정

**Comment by YeonghunKO** [comment]
storage 함수 추가해서 PR날리도록 할게요! 그리고 prop-types 사용가능한지 일단 [qna 깃헙에 ](https://github.com/walking-sunset/wanted-pre-onboarding-qna-7th) 에 물어봤습니다. 아마 기능구현과 직접적인 연관이 없는 라이브러리라 사용가능하긴 할겁니다. 허락되는데로 prop-types도 적용해서 PR 에 올리도록 할게요!

그리고 리드미 개선 아주 깔끔해요!!! 신경써주셔서 감사합니다:))
